export const DC_TESTS_DATA:any = [
        {
            "item_Standard_Code": 100001,
            "item_Standard_Description": "2 D Echocardiography",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "34552-0",
            "item_Description_of_Code": "Cardiac 2D echo panel",
            "item_Correct_Nomenclature": "2D Echocardiography-2D Echo",
        },
        {
            "item_Standard_Code": 100002,
            "item_Standard_Description": "2 D Echocardiography w Doppler",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "18067-9",
            "item_Description_of_Code": "Cardiac echo imaging device Image quality by US",
            "item_Correct_Nomenclature": "2 D Echocardiography w Doppler",
        },
        {
            "item_Standard_Code": 100003,
            "item_Standard_Description": "2 Urine Dipstick (UD)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "50556-0",
            "item_Description_of_Code": "Urinalysis dipstick panel - Urine by Automated test strip",
            "item_Correct_Nomenclature": "Urine Dipstick (UD)",
        },
        {
            "item_Standard_Code": 100005,
            "item_Standard_Description": "3 BP Reading",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3BPR-001",
            "item_Description_of_Code": "3 BP Readings",
            "item_Correct_Nomenclature": "3 BP Readings",
        },
        {
            "item_Standard_Code": 100009,
            "item_Standard_Description": "ABO & Rh (Blood Group & Rh Factor)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "93916-5",
            "item_Description_of_Code": "ABO and Rh group panel - Blood",
            "item_Correct_Nomenclature": "ABO & Rh (Blood Group & Rh Factor)",
        },
        {
            "item_Standard_Code": 100019,
            "item_Standard_Description": "Activated Partial Thromplastin Time (APTT)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "5370-2",
            "item_Description_of_Code": "Streptolysin O Ab [Units/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Antistreptolysin - O (ASO) Titre",
        },
        {
            "item_Standard_Code": 100007,
            "item_Standard_Description": "Alkaline Phosphatase (ALP)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "6768-6",
            "item_Description_of_Code": "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Alkaline Phosphatase (ALP)",
        },
        {
            "item_Standard_Code": 100011,
            "item_Standard_Description": "Alpha Feto Protein",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "48802-3",
            "item_Description_of_Code": "Alpha-1-Fetoprotein panel - Serum or Plasma",
            "item_Correct_Nomenclature": "Alpha Feto Protein-AFP",
        },
        {
            "item_Standard_Code": 100026,
            "item_Standard_Description": "Angiography",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "78895-0",
            "item_Description_of_Code": "Coronary angiography panel",
            "item_Correct_Nomenclature": "CT Coronary Angiography",
        },
        {
            "item_Standard_Code": 100014,
            "item_Standard_Description": "Anti HCV",
            "item_Alias": true,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "75886-2",
            "item_Description_of_Code": "HCV antibody screening - Meaningful Use set",
            "item_Correct_Nomenclature": "Hepatitis C Virus-HCV",
        },
        {
            "item_Standard_Code": 100014,
            "item_Standard_Description": "Anti HCV (IgG)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "16128-1",
            "item_Description_of_Code": "Hepatitis C virus Ab [Presence] in Serum",
            "item_Correct_Nomenclature": "Hepatitis C Virus-HCV IgG",
        },
        {
            "item_Standard_Code": 100102,
            "item_Standard_Description": "Antistreptolysin - O Titre",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "5370-2",
            "item_Description_of_Code": "Streptolysin O Ab [Units/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Antistreptolysin - O (ASO) Titre",
        },
        {
            "item_Standard_Code": 100027,
            "item_Standard_Description": "Arthritic Questionnaire - ARQ",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "ARQ-IP",
            "item_Description_of_Code": "Arthritic Questionnaire - Ipru",
            "item_Correct_Nomenclature": "Arthritic Questionnaire - ARQ",
        },
        {
            "item_Standard_Code": 100028,
            "item_Standard_Description": "Astha Bronchi Questionnaire - ABL",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "ABQ-IP",
            "item_Description_of_Code": "Asthma Bronchi Questionnaire-I Pru",
            "item_Correct_Nomenclature": "Asthma Bronchi Questionnaire - ABL",
        },
        {
            "item_Standard_Code": 100029,
            "item_Standard_Description": "At Client Cost",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "ACC01",
            "item_Description_of_Code": "At client cost",
            "item_Correct_Nomenclature": "At client cost",
        },
        {
            "item_Standard_Code": 100030,
            "item_Standard_Description": "Attending Physician Statement - APS",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "APS-IP",
            "item_Description_of_Code": "Attending Physician Statement-A Pru",
            "item_Correct_Nomenclature": "Attending Physician Statement - APS",
        },
        {
            "item_Standard_Code": 100031,
            "item_Standard_Description": "Audiometry",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "89015-2",
            "item_Description_of_Code": "Pure tone threshold audiometry panel",
            "item_Correct_Nomenclature": "Audiometry/Audiogram",
        },
        {
            "item_Standard_Code": 100033,
            "item_Standard_Description": "Barium Meal",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "78265",
            "item_Description_of_Code": "Stomach Emptying and small bowel transit Study",
            "item_Correct_Nomenclature": "Barium Meal (of Stomach and Small Intestine)",
        },
        {
            "item_Standard_Code": 100034,
            "item_Standard_Description": "Basophil Count ",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "704-7",
            "item_Description_of_Code": "Basophils [#/volume] in Blood by Automated count",
            "item_Correct_Nomenclature": "Basophil Count ",
        },
        {
            "item_Standard_Code": 100016,
            "item_Standard_Description": "Bilirubin (Direct/Conjugated)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "14629-0",
            "item_Description_of_Code": "Bilirubin.direct [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Bilirubin (Direct/Conjugated)",
        },
        {
            "item_Standard_Code": 100017,
            "item_Standard_Description": "Bilirubin (Indirect/Unconjugated)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "14630-8",
            "item_Description_of_Code": "Bilirubin.indirect [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Bilirubin (Indirect/Unconjugated)",
        },
        {
            "item_Standard_Code": 100015,
            "item_Standard_Description": "Bilirubin (Total)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "34543-9",
            "item_Description_of_Code": "Bilirubin direct and total panel [Mass/volume] - Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Bilirubin (Total, Indirect and Direct bilirubin)",
        },
        {
            "item_Standard_Code": 100035,
            "item_Standard_Description": "Bleeding Time (BT)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "11067-6",
            "item_Description_of_Code": "Bleeding time",
            "item_Correct_Nomenclature": "Bleeding Time-BT",
        },
        {
            "item_Standard_Code": 100060,
            "item_Standard_Description": "Blood Nicotine",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "59645-2",
            "item_Description_of_Code": "Cotinine [Presence] in Serum or Plasma by Screen method",
            "item_Correct_Nomenclature": "Serum Cotinine Test (Qualitative)",
        },
        {
            "item_Standard_Code": 100233,
            "item_Standard_Description": "Blood pressure",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "BPR-001",
            "item_Description_of_Code": "Blood Pressure Reading",
            "item_Correct_Nomenclature": "Blood Pressure Reading",
        },
        {
            "item_Standard_Code": 100045,
            "item_Standard_Description": "Blood Sugar (Fasting)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1558-6",
            "item_Description_of_Code": "Fasting glucose [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Fasting Blood Sugar-FBS",
        },
        {
            "item_Standard_Code": 100013,
            "item_Standard_Description": "BUN (Blood Urea Nitrogen)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3094-0",
            "item_Description_of_Code": "Urea nitrogen [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Blood Urea Nitrogen-BUN",
        },
        {
            "item_Standard_Code": 100062,
            "item_Standard_Description": "C-Reactive Protein (CRP)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "11039-5",
            "item_Description_of_Code": "C reactive protein [Presence] in Serum or Plasma",
            "item_Correct_Nomenclature": "C-Reactive Protein (CRP)",
        },
        {
            "item_Standard_Code": 100235,
            "item_Standard_Description": "C.T. Scan of the Abdomen",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "70150",
            "item_Description_of_Code": " CT Abdomen without contrast material",
            "item_Correct_Nomenclature": "C.T. Scan of the Abdomen",
        },
        {
            "item_Standard_Code": 100236,
            "item_Standard_Description": "C.T. Scan of the Head",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "70450",
            "item_Description_of_Code": " CT Head without contrast material",
            "item_Correct_Nomenclature": "C.T. Scan of the Head",
        },
        {
            "item_Standard_Code": 100290,
            "item_Standard_Description": "Carcinoembryonic Antigen",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2039-6",
            "item_Description_of_Code": "Carcinoembryonic Ag [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Carcinoembryonic Antigen (CEA)",
        },
        {
            "item_Standard_Code": 100040,
            "item_Standard_Description": "Carotid Arterial Doppler Study",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "93880",
            "item_Description_of_Code": "Duplex scan of extracranial arteries; complete bilateral study (USV Carotid)",
            "item_Correct_Nomenclature": "Carotid Arterial Doppler Study",
        },
        {
            "item_Standard_Code": 100041,
            "item_Standard_Description": "CBC (Complete Blood Count)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "58410-2",
            "item_Description_of_Code": "CBC panel - Blood by Automated count",
            "item_Correct_Nomenclature": "CBC (Complete Blood Count)-Automated Count",
        },
        {
            "item_Standard_Code": 100042,
            "item_Standard_Description": "CBC with ESR",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "HMG01",
            "item_Description_of_Code": "Haemogram=CBC+ESR=(58410-2+30341-2)",
            "item_Correct_Nomenclature": "Haemogram= CBC+ESR",
        },
        {
            "item_Standard_Code": 100044,
            "item_Standard_Description": "CBC with Peripheral Smear",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "CPBS01",
            "item_Description_of_Code": "CBC+PBS=(58410-2+5909-7)",
            "item_Correct_Nomenclature": "CBC with Peripheral Blood Smear(PBS)",
        },
        {
            "item_Standard_Code": 100047,
            "item_Standard_Description": "Chest Pain Questionnaire (CPQ)",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "CPQ-IP",
            "item_Description_of_Code": "Chest pain Questionnaire- IPru",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100012,
            "item_Standard_Description": "Chest X-ray PA & lateral view",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "71010",
            "item_Description_of_Code": "Radiologic examination, chest; single view, frontal",
            "item_Correct_Nomenclature": "Chest X-ray PA & lateral view",
        },
        {
            "item_Standard_Code": 100048,
            "item_Standard_Description": "Child MER",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "CMER",
            "item_Description_of_Code": "Child MER",
            "item_Correct_Nomenclature": "Child MER/Juvenile MER",
        },
        {
            "item_Standard_Code": 100049,
            "item_Standard_Description": "Cholesterol/HDL Ratio",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "9830-1",
            "item_Description_of_Code": "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma",
            "item_Correct_Nomenclature": "Cholesterol.total:Cholesterol in HDL Ratio",
        },
        {
            "item_Standard_Code": 100050,
            "item_Standard_Description": "Clotting Time (CT)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3184-9",
            "item_Description_of_Code": "Activated clotting time (ACT) of Blood by Coagulation assay",
            "item_Correct_Nomenclature": "Clotting Time-CT",
        },
        {
            "item_Standard_Code": 100051,
            "item_Standard_Description": "CNS Questionnaire",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "CNSQ-IP",
            "item_Description_of_Code": "CNS Questionnaire-I Pru",
            "item_Correct_Nomenclature": "CNS Questionnaire-I Pru",
        },
        {
            "item_Standard_Code": 100052,
            "item_Standard_Description": "Colour Doppler - Lower Limbs",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "93925",
            "item_Description_of_Code": "Duplex scan of lower extremity arteries orarterial bypass grafts; complete bilateral study",
            "item_Correct_Nomenclature": "Colour Doppler - Lower Limbs",
        },
        {
            "item_Standard_Code": 100053,
            "item_Standard_Description": "Colour Doppler - Upper Abdomen",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "93975",
            "item_Description_of_Code": "Abdomen Doppler",
            "item_Correct_Nomenclature": "Colour Doppler - Upper Abdomen",
        },
        {
            "item_Standard_Code": 100056,
            "item_Standard_Description": "Coombs Test",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1007-4",
            "item_Description_of_Code": "Direct antiglobulin test.polyspecific reagent [Presence] on Red Blood Cells",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100057,
            "item_Standard_Description": "Copper",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "5631-7",
            "item_Description_of_Code": "Copper [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Copper",
        },
        {
            "item_Standard_Code": 100061,
            "item_Standard_Description": "Courier Charges",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "CC01",
            "item_Description_of_Code": "Courier Charges",
            "item_Correct_Nomenclature": "Courier Charges",
        },
        {
            "item_Standard_Code": 100063,
            "item_Standard_Description": "Creatinine Clearance Test",
            "item_Alias": false,
            "item_Type_of_Code": "nan",
            "item_Final_Code": "2164-2",
            "item_Description_of_Code": "Creatinine renal clearance in 24 hour Urine and Serum or Plasma",
            "item_Correct_Nomenclature": "Creatinine Clearance Test",
        },
        {
            "item_Standard_Code": 100064,
            "item_Standard_Description": "Creatinine Phosphokinase",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2157-6",
            "item_Description_of_Code": "Creatine kinase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Creatinine Phosphokinase (CPK)",
        },
        {
            "item_Standard_Code": 100065,
            "item_Standard_Description": "CT Scan - Abdomen",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "74150",
            "item_Description_of_Code": "Computed Tomography Abdomen without contrast",
            "item_Correct_Nomenclature": "CT Scan - Abdomen",
        },
        {
            "item_Standard_Code": 100066,
            "item_Standard_Description": "CT Scan - Chest",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "71250",
            "item_Description_of_Code": "Computed tomography, thorax, diagnostic; without contrast material",
            "item_Correct_Nomenclature": "CT Scan - Chest/Thorax",
        },
        {
            "item_Standard_Code": 100067,
            "item_Standard_Description": "CT Scan - Head",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "70450",
            "item_Description_of_Code": "Computed Tomography Head or Brian without contrast material",
            "item_Correct_Nomenclature": "CT Scan - Head",
        },
        {
            "item_Standard_Code": 100068,
            "item_Standard_Description": "CT Scan - Thorax",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "71250",
            "item_Description_of_Code": "Computed tomography, thorax, diagnostic; without contrast material",
            "item_Correct_Nomenclature": "CT Scan - Chest",
        },
        {
            "item_Standard_Code": 100069,
            "item_Standard_Description": "Deformity Questionnaire - DEF",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "DEFQ-IP",
            "item_Description_of_Code": "Deformity Questionnaire- I Pru",
            "item_Correct_Nomenclature": "Deformity Questionnaire - DEF",
        },
        {
            "item_Standard_Code": 100070,
            "item_Standard_Description": "Diabetes Questionnaire - DIQ",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "DMQ-IP",
            "item_Description_of_Code": "Diabetes Questionnaire- I Pru",
            "item_Correct_Nomenclature": "Diabetes Questionnaire - DIQ",
        },
        {
            "item_Standard_Code": 100072,
            "item_Standard_Description": "Differential Leucocyte Count",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "26471-3",
            "item_Description_of_Code": "Leukocytes other/100 leukocytes in Blood",
            "item_Correct_Nomenclature": "Differential Leucocyte Count-DLC",
        },
        {
            "item_Standard_Code": 100238,
            "item_Standard_Description": "Discharge Card & Summary sheet",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "DCSS02",
            "item_Description_of_Code": "Discharge Card & Summary sheet",
            "item_Correct_Nomenclature": "Discharge Card & Summary sheet",
        },
        {
            "item_Standard_Code": 100074,
            "item_Standard_Description": "Dobutamine Stress Echocardiography",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "93352",
            "item_Description_of_Code": "Use of echocardiographic contrast agent during stress echocardiography",
            "item_Correct_Nomenclature": "Dobutamine Stress Echocardiogram - DSE",
        },
        {
            "item_Standard_Code": 100075,
            "item_Standard_Description": "e GFR",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "98979-8",
            "item_Description_of_Code": "Glomerular filtration rate/1.73 sq M.predicted [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI 2021)",
            "item_Correct_Nomenclature": "Estimated Glomerular filtration rate (eGFR)",
        },
        {
            "item_Standard_Code": 100076,
            "item_Standard_Description": "ECG",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "11524-6",
            "item_Description_of_Code": "EKG study",
            "item_Correct_Nomenclature": "Electocardiogram-ECG",
        },
        {
            "item_Standard_Code": 100079,
            "item_Standard_Description": "EEG",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "11523-8",
            "item_Description_of_Code": "EEG study",
            "item_Correct_Nomenclature": "Electroencephalography study-EEG",
        },
        {
            "item_Standard_Code": 100010,
            "item_Standard_Description": "Eosinophil Count (AEC)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "713-8",
            "item_Description_of_Code": "Eosinophils/100 leukocytes in Blood by Automated count",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100080,
            "item_Standard_Description": "Epilepsy Questionnaire",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "EPQ-IP",
            "item_Description_of_Code": "Epilepsy Questionnaire-I Pru",
            "item_Correct_Nomenclature": "Epilepsy Questionnaire",
        },
        {
            "item_Standard_Code": 100081,
            "item_Standard_Description": "Epstein-Barr virus antigen",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "7882-4",
            "item_Description_of_Code": "Epstein Barr virus early Ab [Presence] in Serum",
            "item_Correct_Nomenclature": "Epstein-Barr virus antigen",
        },
        {
            "item_Standard_Code": 100082,
            "item_Standard_Description": "Erythrocyte Count",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "789-8",
            "item_Description_of_Code": "Erythrocytes [#/volume] in Blood by Automated count",
            "item_Correct_Nomenclature": "Erythrocyte Count/Red Blood Cell Count",
        },
        {
            "item_Standard_Code": 100083,
            "item_Standard_Description": "Escort charges for VIP customers",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "SCVIPC01",
            "item_Description_of_Code": "Escort charges for VIP customers",
            "item_Correct_Nomenclature": "Escort charges for VIP customers",
        },
        {
            "item_Standard_Code": 100043,
            "item_Standard_Description": "ESR",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "30341-2",
            "item_Description_of_Code": "Erythrocyte sedimentation rate",
            "item_Correct_Nomenclature": "Erythrocyte Sedimentation Rate-ESR",
        },
        {
            "item_Standard_Code": 100084,
            "item_Standard_Description": "Eye examination",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "EE-001",
            "item_Description_of_Code": "Eye examination",
            "item_Correct_Nomenclature": "Eye examination",
        },
        {
            "item_Standard_Code": 100085,
            "item_Standard_Description": "Follicle Stimulating Hormone",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "15067-2",
            "item_Description_of_Code": "Follitropin [Units/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Follicle Stimulating Hormone (FSH)",
        },
        {
            "item_Standard_Code": 100089,
            "item_Standard_Description": "Fundoscopy",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "LP149841-1",
            "item_Description_of_Code": "Ophthalmoscopy",
            "item_Correct_Nomenclature": "Fundoscopy",
        },
        {
            "item_Standard_Code": 100090,
            "item_Standard_Description": "G6PD Qualitative",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2356-4",
            "item_Description_of_Code": "Glucose-6-Phosphate dehydrogenase [Presence] in Red Blood Cells",
            "item_Correct_Nomenclature": "G6PD (Glucose-6-Phosphate dehydrogenase) Qualitative",
        },
        {
            "item_Standard_Code": 100091,
            "item_Standard_Description": "G6PD Quantitative",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2359-8",
            "item_Description_of_Code": "Glucose-6-Phosphate dehydrogenase [Enzymatic activity/volume] in Serum",
            "item_Correct_Nomenclature": "G6PD (Glucose-6-Phosphate dehydrogenase) Quantitative",
        },
        {
            "item_Standard_Code": 100092,
            "item_Standard_Description": "GGTP (Gamma Glutamyl TransPeptidase)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2324-2",
            "item_Description_of_Code": "Gamma glutamyl transferase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Gamma-Glutamyl Transpeptidase-GGTP",
        },
        {
            "item_Standard_Code": 100093,
            "item_Standard_Description": "Goitre",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "GOITQ-IP",
            "item_Description_of_Code": "Goitre Questionnaire-I Pru",
            "item_Correct_Nomenclature": "Goitre Questionnaire - GOQ",
        },
        {
            "item_Standard_Code": 100094,
            "item_Standard_Description": "Gynaecologist Questionnaire",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "GYNQ-IP",
            "item_Description_of_Code": "Gynaecologist Questionnaire- I Pru",
            "item_Correct_Nomenclature": "Gynaecologist Questionnaire - GYQ",
        },
        {
            "item_Standard_Code": 100095,
            "item_Standard_Description": "Haemoglobin (Hb)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "718-7",
            "item_Description_of_Code": "Hemoglobin [Mass/volume] in Blood",
            "item_Correct_Nomenclature": "Haemoglobin-Hb",
        },
        {
            "item_Standard_Code": 100096,
            "item_Standard_Description": "Haemogram",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "HMG01",
            "item_Description_of_Code": "Haemogram=CBC+ESR=(58410-2+30341-2)",
            "item_Correct_Nomenclature": "Haemogram= CBC+ESR",
        },
        {
            "item_Standard_Code": 100097,
            "item_Standard_Description": "HbA1c",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "4548-4",
            "item_Description_of_Code": "Hemoglobin A1c/Hemoglobin.total in Blood",
            "item_Correct_Nomenclature": "Glycosylated Haemoglobin-HbA1c",
        },
        {
            "item_Standard_Code": 100098,
            "item_Standard_Description": "Hbeag",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "13954-3",
            "item_Description_of_Code": "Hepatitis B virus e Ag [Presence] in Serum or Plasma by Immunoassay",
            "item_Correct_Nomenclature": "Hepatitis B e antigen-HBeAg",
        },
        {
            "item_Standard_Code": 100032,
            "item_Standard_Description": "HbSAg (Australia Antigen)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "70154-0",
            "item_Description_of_Code": "Hepatitis B virus surface Ag in Serum or Plasma by Confirmatory method",
            "item_Correct_Nomenclature": "Hepatitis B surface antigen (HBsAg), formerly Australia antigen",
        },
        {
            "item_Standard_Code": 100099,
            "item_Standard_Description": "HBV",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "LG32752-4",
            "item_Description_of_Code": "Hepatitis B virus",
            "item_Correct_Nomenclature": "Hepatitis B Virus (HBV)",
        },
        {
            "item_Standard_Code": 100100,
            "item_Standard_Description": "HBV DNA",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "95147-5",
            "item_Description_of_Code": "Hepatitis B virus DNA panel - Serum or Plasma A",
            "item_Correct_Nomenclature": "Hepatitis B Virus DNA (HBV DNA)",
        },
        {
            "item_Standard_Code": 100101,
            "item_Standard_Description": "HCV (RNA)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "50023-1",
            "item_Description_of_Code": "Hepatitis C virus RNA panel (viral load) in Serum or Plasma by NAA with probe detection",
            "item_Correct_Nomenclature": "Hepatitis C Virus RNA )HBV RNA)",
        },
        {
            "item_Standard_Code": 100243,
            "item_Standard_Description": "HCV RIBA",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "75887-0",
            "item_Description_of_Code": "HCV antibody RIBA tests - Meaningful Use set by Immunoblot",
            "item_Correct_Nomenclature": "Hepatitis C Virus RIBA",
        },
        {
            "item_Standard_Code": 100105,
            "item_Standard_Description": "HCV(Hepatitis C Virus)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "LG32754-0",
            "item_Description_of_Code": "Hepatitis C virus",
            "item_Correct_Nomenclature": "Hepatitis C virus (HCV)",
        },
        {
            "item_Standard_Code": 100077,
            "item_Standard_Description": "HDL Cholesterol",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2085-9",
            "item_Description_of_Code": "Cholesterol in HDL [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "High Density Lipoprotein (HDL)",
        },
        {
            "item_Standard_Code": 100244,
            "item_Standard_Description": "Hearing Questionnaire",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "HEAQ-01",
            "item_Description_of_Code": "Hearing Questionnaire",
            "item_Correct_Nomenclature": "Hearing Questionnaire",
        },
        {
            "item_Standard_Code": 100103,
            "item_Standard_Description": "Height & Weight",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "WTHT-001",
            "item_Description_of_Code": "Height & Weight",
            "item_Correct_Nomenclature": "Height & Weight",
        },
        {
            "item_Standard_Code": 100104,
            "item_Standard_Description": "Hematocrit (PCV)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "20570-8",
            "item_Description_of_Code": "Hematocrit [Volume Fraction] of Blood",
            "item_Correct_Nomenclature": "Hematocri/Packed Cell Volume(PCV)",
        },
        {
            "item_Standard_Code": 100107,
            "item_Standard_Description": "HIV 1 & 2 (Elisa)",
            "item_Alias": true,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "89365-1",
            "item_Description_of_Code": "HIV 1 and 2 Ab panel - Serum, Plasma or Blood by Rapid immunoassay",
            "item_Correct_Nomenclature": "Human immunodeficiency virus- HIV I and II",
        },
        {
            "item_Standard_Code": 100108,
            "item_Standard_Description": "HIV Western Blot",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "77685-6",
            "item_Description_of_Code": "HIV 1 and 2 IgG Ab [Identifier] in Serum or Plasma by Immunoblot",
            "item_Correct_Nomenclature": "Western Blot Test for HIV ",
        },
        {
            "item_Standard_Code": 100115,
            "item_Standard_Description": "Home Visit by a Technician",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "HV-LT-01",
            "item_Description_of_Code": "Home Visit Technician(Lab)",
            "item_Correct_Nomenclature": "Home Visit Technician(Lab)",
        },
        {
            "item_Standard_Code": 100109,
            "item_Standard_Description": "Home Visit by an ECG Technician",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "HV-ECGT-01",
            "item_Description_of_Code": "Home Visit by ECG Technician",
            "item_Correct_Nomenclature": "Home Visit ECG Technician",
        },
        {
            "item_Standard_Code": 100110,
            "item_Standard_Description": "Home Visit by MBBS",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "HV-DR-01",
            "item_Description_of_Code": "Home Visit Physician/Doctor",
            "item_Correct_Nomenclature": "Added",
        },
        {
            "item_Standard_Code": 100117,
            "item_Standard_Description": "HR CT Scan - Chest",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "71250-1",
            "item_Description_of_Code": "Computed tomography, thorax, diagnostic; without contrast material (High Resolutution CT Chest)",
            "item_Correct_Nomenclature": "HR CT Scan - Chest",
        },
        {
            "item_Standard_Code": 100118,
            "item_Standard_Description": "Hydroxy Butyrate DeHydrogenase (HBDH)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1682-4",
            "item_Description_of_Code": "Beta hydroxybutyrate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Hydroxy Butyrate DeHydrogenase-HBDH ",
        },
        {
            "item_Standard_Code": 100120,
            "item_Standard_Description": "Hypertension Questionnaire",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "HTNQ-IP",
            "item_Description_of_Code": "Hypertension Questionnaire- Ipru",
            "item_Correct_Nomenclature": "Hypertension Questionnaire",
        },
        {
            "item_Standard_Code": 100121,
            "item_Standard_Description": "Iron/TIBC",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "50190-8",
            "item_Description_of_Code": "Iron and Iron binding capacity panel - Serum or Plasma",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100123,
            "item_Standard_Description": "Kidney Function Test (KFT)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "24362-6",
            "item_Description_of_Code": "Renal function 2000 panel - Serum or Plasma",
            "item_Correct_Nomenclature": "Renal Function Test/Kidney Function Test - RFT/KFT",
        },
        {
            "item_Standard_Code": 100125,
            "item_Standard_Description": "LDH",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2532-0",
            "item_Description_of_Code": "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Lactate dehydrogenase-LDH",
        },
        {
            "item_Standard_Code": 100126,
            "item_Standard_Description": "LDL",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2089-1",
            "item_Description_of_Code": "Cholesterol in LDL [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Low density lipoprotein (LDL)",
        },
        {
            "item_Standard_Code": 100127,
            "item_Standard_Description": "Lipid Profile",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "100898-6",
            "item_Description_of_Code": "Lipid panel - Serum or Plasma",
            "item_Correct_Nomenclature": "Lipid Profile/Lipids",
        },
        {
            "item_Standard_Code": 100128,
            "item_Standard_Description": "Liver Function Test",
            "item_Alias": true,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "24325-3",
            "item_Description_of_Code": "Hepatic function 2000 panel - Serum or Plasma",
            "item_Correct_Nomenclature": "Liver Function Test-LFT",
        },
        {
            "item_Standard_Code": 100129,
            "item_Standard_Description": "Luetenizing Hormone (LH)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "10501-5",
            "item_Description_of_Code": "Lutropin [Units/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Luetenizing Hormone-LH",
        },
        {
            "item_Standard_Code": 100130,
            "item_Standard_Description": "Lymphocyte",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "26474-7",
            "item_Description_of_Code": "Lymphocytes [#/volume] in Blood",
            "item_Correct_Nomenclature": "Lymphocyte",
        },
        {
            "item_Standard_Code": 100131,
            "item_Standard_Description": "Magnesium (Mg)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2601-3",
            "item_Description_of_Code": "Magnesium [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Magnesium (Mg)",
        },
        {
            "item_Standard_Code": 100132,
            "item_Standard_Description": "Mammography",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "24606-6",
            "item_Description_of_Code": "MG Breast Screening",
            "item_Correct_Nomenclature": "Mammography or X Ray Breast (Bilateral)",
        },
        {
            "item_Standard_Code": 100133,
            "item_Standard_Description": "Mantoux Test",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "39263-9",
            "item_Description_of_Code": "Tuberculin screen test status CPHS",
            "item_Correct_Nomenclature": "Mantoux Test / Tuberculin Test",
        },
        {
            "item_Standard_Code": 100134,
            "item_Standard_Description": "MCHC",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "28540-3",
            "item_Description_of_Code": "MCHC [Mass/volume]",
            "item_Correct_Nomenclature": "Mean Corpuscular Hemoglobin Concentration(MCHC)",
        },
        {
            "item_Standard_Code": 100135,
            "item_Standard_Description": "MCV",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "787-2",
            "item_Description_of_Code": "MCV [Entitic volume] by Automated count",
            "item_Correct_Nomenclature": "Mean Corpuscular Volume-MCV",
        },
        {
            "item_Standard_Code": 100136,
            "item_Standard_Description": "Mean Corpuscular Haemoglobin (MCH)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "785-6",
            "item_Description_of_Code": "MCH [Entitic mass] by Automated count.",
            "item_Correct_Nomenclature": "Mean Corpuscular Hemoglobin-MCH",
        },
        {
            "item_Standard_Code": 100038,
            "item_Standard_Description": "Medical Examination Report - MER",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "MER-001",
            "item_Description_of_Code": "Medical Examination Report",
            "item_Correct_Nomenclature": "Medical Examination Report",
        },
        {
            "item_Standard_Code": 100022,
            "item_Standard_Description": "MicroAlbumin (Urine)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "14957-5",
            "item_Description_of_Code": "Microalbumin [Mass/volume] in Urine",
            "item_Correct_Nomenclature": "Urine Microalbumin",
        },
        {
            "item_Standard_Code": 100251,
            "item_Standard_Description": "Midstream Urine Analysis",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "24356-8",
            "item_Description_of_Code": "Urinalysis complete panel - Urine",
            "item_Correct_Nomenclature": "Routine Urine Analysis-(RUA)/Midstream Urine Analysis (MSU)",
        },
        {
            "item_Standard_Code": 100137,
            "item_Standard_Description": "Monocyte",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "26485-3",
            "item_Description_of_Code": "Monocytes/100 leukocytes in Blood",
            "item_Correct_Nomenclature": "Monocyte",
        },
        {
            "item_Standard_Code": 100138,
            "item_Standard_Description": "MRI - Head",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "70551",
            "item_Description_of_Code": "MRI Brain without contrast material",
            "item_Correct_Nomenclature": "MRI Head/Brian",
        },
        {
            "item_Standard_Code": 100139,
            "item_Standard_Description": "Neutrophil",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "26499-4",
            "item_Description_of_Code": "Neutrophils [#/volume] in Blood",
            "item_Correct_Nomenclature": "Neutrophil",
        },
        {
            "item_Standard_Code": 100278,
            "item_Standard_Description": "Nicotine Sample Collection",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "NSC-001",
            "item_Description_of_Code": "Nicotine Sample Collection",
            "item_Correct_Nomenclature": "Nicotine Sample Collection",
        },
        {
            "item_Standard_Code": 100140,
            "item_Standard_Description": "NT-proBNP",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "33762-6",
            "item_Description_of_Code": "Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "NT-proBNP",
        },
        {
            "item_Standard_Code": 100142,
            "item_Standard_Description": "Ophthalmic Questionnaire",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "OPQ-IP-001",
            "item_Description_of_Code": "Ophthalmic Questionnaire",
            "item_Correct_Nomenclature": "Ophthalmic Questionnaire",
        },
        {
            "item_Standard_Code": 100143,
            "item_Standard_Description": "Opthalmic Consultation",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "OPC-001",
            "item_Description_of_Code": "Ophthalmic Consultation",
            "item_Correct_Nomenclature": "Ophthalmic Consultation",
        },
        {
            "item_Standard_Code": 100144,
            "item_Standard_Description": "Oral Cavity",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "ORC-001",
            "item_Description_of_Code": "Examination of Oral Cavity",
            "item_Correct_Nomenclature": "Examination of Oral Cavity",
        },
        {
            "item_Standard_Code": 100055,
            "item_Standard_Description": "Oral Glucose Tolerance Test (OGTT)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "21004-7",
            "item_Description_of_Code": "Glucose tolerance [Interpretation] in Serum or Plasma",
            "item_Correct_Nomenclature": "Oral Glucose Tolerance Test-OGTT/GTT",
        },
        {
            "item_Standard_Code": 100020,
            "item_Standard_Description": "Partial Thromboplastin Time (PTT)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3173-2",
            "item_Description_of_Code": "aPTT in Blood by Coagulation assay",
            "item_Correct_Nomenclature": "Partial Thromboplastin Time-PTT",
        },
        {
            "item_Standard_Code": 100145,
            "item_Standard_Description": "Peripheral Blood Smear",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "5909-7",
            "item_Description_of_Code": "Blood smear finding [Identifier] in Blood by Light microscopy",
            "item_Correct_Nomenclature": "Peripheral Blood Smear (PBS)",
        },
        {
            "item_Standard_Code": 100153,
            "item_Standard_Description": "PFT (Pulmonary Function Test / Spirometry)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "81459-0",
            "item_Description_of_Code": "Spirometry panel",
            "item_Correct_Nomenclature": "Pulmonary Function Test (PFT)/ Spirometry",
        },
        {
            "item_Standard_Code": 100146,
            "item_Standard_Description": "Photograph/s",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "PH-01",
            "item_Description_of_Code": "Photograph/s",
            "item_Correct_Nomenclature": "Photograph/s",
        },
        {
            "item_Standard_Code": 100149,
            "item_Standard_Description": "Platelets",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "777-3",
            "item_Description_of_Code": "Platelets [#/volume] in Blood by Automated count",
            "item_Correct_Nomenclature": "Platelets",
        },
        {
            "item_Standard_Code": 100150,
            "item_Standard_Description": "Post Glucose Blood Sugar (PGBS)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "20436-2",
            "item_Description_of_Code": "Glucose [Mass/volume] in Serum or Plasma --2 hours post dose glucose",
            "item_Correct_Nomenclature": "Post Glucose Blood Sugar-PGBS",
        },
        {
            "item_Standard_Code": 100046,
            "item_Standard_Description": "Post Prandial Blood Sugar (PPBS)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1521-4",
            "item_Description_of_Code": "Glucose [Mass/volume] in Serum or Plasma --2 hours post meal",
            "item_Correct_Nomenclature": "Post Prandial Blood Sugar-PPBS",
        },
        {
            "item_Standard_Code": 100087,
            "item_Standard_Description": "Prostate Specific Antigen (PSA)",
            "item_Alias": true,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2857-1",
            "item_Description_of_Code": "Prostate specific Ag [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Prostate Specific Antigen-PSA",
        },
        {
            "item_Standard_Code": 100152,
            "item_Standard_Description": "Prothrombin",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "5902-2",
            "item_Description_of_Code": "Prothrombin time (PT)",
            "item_Correct_Nomenclature": "Prothrombin time-PT",
        },
        {
            "item_Standard_Code": 100256,
            "item_Standard_Description": "QSTN-CENTRAL NERVOUS SYSTEM - QCN",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "CNSQ-IP",
            "item_Description_of_Code": "CNS Questionnaire-I Pru",
            "item_Correct_Nomenclature": "CNS Questionnaire-I Pru",
        },
        {
            "item_Standard_Code": 100154,
            "item_Standard_Description": "RA Factor",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "33910-1 ",
            "item_Description_of_Code": "Rheumatoid factor [Presence] in Serum",
            "item_Correct_Nomenclature": "Rheumatoid Arthritis factor (RA factor)",
        },
        {
            "item_Standard_Code": 100155,
            "item_Standard_Description": "Random Blood Sugar (RBS)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2345-7",
            "item_Description_of_Code": "Glucose [Mass/volume] in Serum or Plasma.",
            "item_Correct_Nomenclature": "Random Blood Sugar-RBS",
        },
        {
            "item_Standard_Code": 100258,
            "item_Standard_Description": "Red Cell Distribution Width",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "21000-5",
            "item_Description_of_Code": "Erythrocyte distribution width [Entitic volume] by Automated count",
            "item_Correct_Nomenclature": "Red Cell Distribution Width",
        },
        {
            "item_Standard_Code": 100157,
            "item_Standard_Description": "Renal Function test",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "24362-6",
            "item_Description_of_Code": "Renal function 2000 panel - Serum or Plasma",
            "item_Correct_Nomenclature": "Renal/Kidney Function Test - RFT/KFT",
        },
        {
            "item_Standard_Code": 100262,
            "item_Standard_Description": "RESPIRATORY DISORDER QUSTNRE - RES",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "RDQ-IP",
            "item_Description_of_Code": "Respiratory Disorder Questionnaire-I Pru",
            "item_Correct_Nomenclature": "Respiratory Disorder Questionnaire-I Pru",
        },
        {
            "item_Standard_Code": 100263,
            "item_Standard_Description": "Reticulocyte count",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "14196-0",
            "item_Description_of_Code": "Reticulocytes [#/volume] in Blood",
            "item_Correct_Nomenclature": "Reticulocyte count",
        },
        {
            "item_Standard_Code": 100158,
            "item_Standard_Description": "Routine Stool Test",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "88847-9",
            "item_Description_of_Code": "Microbiology CNAMTS panel - Stool",
            "item_Correct_Nomenclature": "Routine Stool Test",
        },
        {
            "item_Standard_Code": 100160,
            "item_Standard_Description": "Scan Charges",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "SC-01",
            "item_Description_of_Code": "Scan Charges",
            "item_Correct_Nomenclature": "Scan Charges",
        },
        {
            "item_Standard_Code": 100161,
            "item_Standard_Description": "Serum Acid Phosphatase (ACD)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1715-2",
            "item_Description_of_Code": "Acid phosphatase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Acid Phosphatase ",
        },
        {
            "item_Standard_Code": 100021,
            "item_Standard_Description": "Serum Albumin",
            "item_Alias": false,
            "item_Type_of_Code": "1751-7",
            "item_Final_Code": "Albumin [Mass/volume] in Serum or Plasma",
            "item_Description_of_Code": "Proteins (Albumin) considered as Serum Albumin",
            "item_Correct_Nomenclature": "Serum Albumin",
        },
        {
            "item_Standard_Code": 100018,
            "item_Standard_Description": "Serum Amylase",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1798-8",
            "item_Description_of_Code": "Amylase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Amylase",
        },
        {
            "item_Standard_Code": 100277,
            "item_Standard_Description": "Serum Aspergillus Fumigatus Ig E Level",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "6025-1",
            "item_Description_of_Code": "Aspergillus fumigatus IgE Ab [Units/volume] in Serum",
            "item_Correct_Nomenclature": "Serum Aspergillus Fumigatus Ig E Level",
        },
        {
            "item_Standard_Code": 100037,
            "item_Standard_Description": "Serum Calcium",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "17861-6",
            "item_Description_of_Code": "Calcium [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Calcium",
        },
        {
            "item_Standard_Code": 100164,
            "item_Standard_Description": "Serum Chlorides",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2078-4",
            "item_Description_of_Code": "Chloride [Moles/volume] in Urine",
            "item_Correct_Nomenclature": "Serum Chloride",
        },
        {
            "item_Standard_Code": 100165,
            "item_Standard_Description": "Serum Cholesterol",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2093-3",
            "item_Description_of_Code": "Cholesterol [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Cholesterol total",
        },
        {
            "item_Standard_Code": 100166,
            "item_Standard_Description": "Serum Creatinine",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2160-0",
            "item_Description_of_Code": "Creatinine [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Creatinine",
        },
        {
            "item_Standard_Code": 100167,
            "item_Standard_Description": "Serum Creatinine Phosphokinase (CPK)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2157-6",
            "item_Description_of_Code": "Creatine kinase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Creatinine Phosphokinase (CPK)",
        },
        {
            "item_Standard_Code": 100168,
            "item_Standard_Description": "Serum Electrolytes",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "55231-5",
            "item_Description_of_Code": "Electrolytes panel - Blood",
            "item_Correct_Nomenclature": "Serum Electrolytes",
        },
        {
            "item_Standard_Code": 100169,
            "item_Standard_Description": "Serum Ferritin",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2276-4",
            "item_Description_of_Code": "Ferritin [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Ferritin",
        },
        {
            "item_Standard_Code": 100170,
            "item_Standard_Description": "Serum Globulin",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": " 2336-6 ",
            "item_Description_of_Code": "Globulin [Mass/volume] in Serum",
            "item_Correct_Nomenclature": "Serum Globulin",
        },
        {
            "item_Standard_Code": 100171,
            "item_Standard_Description": "Serum Homocystine",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "13965-9",
            "item_Description_of_Code": "Homocysteine [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Homocystine",
        },
        {
            "item_Standard_Code": 100172,
            "item_Standard_Description": "Serum Lipase",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3040-3",
            "item_Description_of_Code": "Lipase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Lipase",
        },
        {
            "item_Standard_Code": 100215,
            "item_Standard_Description": "Serum Phosphorus",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2777-1",
            "item_Description_of_Code": "Phosphate [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Phosphorus",
        },
        {
            "item_Standard_Code": 100173,
            "item_Standard_Description": "Serum Potassium",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2823-3",
            "item_Description_of_Code": "Potassium [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Potassium",
        },
        {
            "item_Standard_Code": 100174,
            "item_Standard_Description": "Serum Prolactin Level",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2842-3",
            "item_Description_of_Code": "Prolactin [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Prolactin",
        },
        {
            "item_Standard_Code": 100175,
            "item_Standard_Description": "Serum Protein",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2885-2",
            "item_Description_of_Code": "Protein [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Protein ",
        },
        {
            "item_Standard_Code": 100176,
            "item_Standard_Description": "Serum Sodium",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2951-2",
            "item_Description_of_Code": "Sodium [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Sodium",
        },
        {
            "item_Standard_Code": 100177,
            "item_Standard_Description": "Serum Triglycerides",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2571-8",
            "item_Description_of_Code": "Triglyceride [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Triglycerides",
        },
        {
            "item_Standard_Code": 100178,
            "item_Standard_Description": "Serum Uric Acid",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3084-1",
            "item_Description_of_Code": "Urate [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Uric Acid",
        },
        {
            "item_Standard_Code": 100179,
            "item_Standard_Description": "SGOT",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1920-8",
            "item_Description_of_Code": "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Glutamic oxaloacetic transaminase (SGOT) /Aspartate Aminotransferase (AST)",
        },
        {
            "item_Standard_Code": 100180,
            "item_Standard_Description": "SGPT",
            "item_Alias": true,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "1742-6",
            "item_Description_of_Code": "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum glutamic pyruvic transaminase (SGPT) / AlanineAminotransferase (ALT)",
        },
        {
            "item_Standard_Code": 100181,
            "item_Standard_Description": "Sonomammogram",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "26214-7",
            "item_Description_of_Code": "US Breast- Bilateral",
            "item_Correct_Nomenclature": "Sonomammogram? USG of both breasts",
        },
        {
            "item_Standard_Code": 100183,
            "item_Standard_Description": "Sputum Routine",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "33455-7",
            "item_Description_of_Code": "Appearance of Sputum",
            "item_Correct_Nomenclature": "Sputum Routine",
        },
        {
            "item_Standard_Code": 100184,
            "item_Standard_Description": "Stress Thallium",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "82654-5",
            "item_Description_of_Code": "Cardiac nuclear imaging SPECT panel",
            "item_Correct_Nomenclature": "Stress Thallium",
        },
        {
            "item_Standard_Code": 100185,
            "item_Standard_Description": "T3",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3053-6",
            "item_Description_of_Code": "Triiodothyronine (T3) [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100088,
            "item_Standard_Description": "T4",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "3026-2",
            "item_Description_of_Code": "Thyroxine (T4) [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100267,
            "item_Standard_Description": "Tele Mer",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "TMER-001",
            "item_Description_of_Code": "Tele-Medical Examination Report",
            "item_Correct_Nomenclature": "Tele-Medical Examination Report",
        },
        {
            "item_Standard_Code": 100186,
            "item_Standard_Description": "Thyroid Profile",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "ALTFT-3",
            "item_Description_of_Code": "Thyroid Profile as a package is not there in code, hence use combination of T3,T4 & TSH ",
            "item_Correct_Nomenclature": "Thyroid Profile",
        },
        {
            "item_Standard_Code": 100086,
            "item_Standard_Description": "Thyroid Stimulating Hormone",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "11580-8",
            "item_Description_of_Code": "Thyrotropin [Units/volume] in Serum or Plasma by Detection limit <= 0.005 mIU/L",
            "item_Correct_Nomenclature": "Thyroid Stimulating Hormone (TSH)",
        },
        {
            "item_Standard_Code": 100015,
            "item_Standard_Description": "Total Bilirubin",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "14631-6",
            "item_Description_of_Code": "Bilirubin.total [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Serum Bilirubin (Total)",
        },
        {
            "item_Standard_Code": 100188,
            "item_Standard_Description": "Total Leucocyte Count",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "26464-8",
            "item_Description_of_Code": "Leukocytes [#/volume] in Blood",
            "item_Correct_Nomenclature": "Total Leucocyte Count - TLC",
        },
        {
            "item_Standard_Code": 100189,
            "item_Standard_Description": "Total Proteins",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "LP32144-5",
            "item_Description_of_Code": "Protein.total",
            "item_Correct_Nomenclature": "Total Proteins",
        },
        {
            "item_Standard_Code": 100006,
            "item_Standard_Description": "Tread Mill Test (TMT)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "18752-6",
            "item_Description_of_Code": "Exercise stress test study",
            "item_Correct_Nomenclature": "Treadmill Exercise ECG - TMT/Stress Test",
        },
        {
            "item_Standard_Code": 100270,
            "item_Standard_Description": "Tuberculosis Questionnaire - TBQ",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "TBQ-IP",
            "item_Description_of_Code": "Tuberculosis Questionnaire-I Pru",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100272,
            "item_Standard_Description": "Ulcer Questions By Examiner - ULM",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "UQBE-IP",
            "item_Description_of_Code": "Ulcer Questions By Examiner-I Pru",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100008,
            "item_Standard_Description": "Ultrasound - Abdomen",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "76700",
            "item_Description_of_Code": "Ultrasound, abdominal, real time with image documentation; complete",
            "item_Correct_Nomenclature": "USG - Abdomen & Pelvis (Whole Abdomen) ",
        },
        {
            "item_Standard_Code": 100191,
            "item_Standard_Description": "Ultrasound - Chest",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "76604",
            "item_Description_of_Code": "Diagnostic Ultrasound Procedures of the Chest.",
            "item_Correct_Nomenclature": "USG Chest",
        },
        {
            "item_Standard_Code": 100124,
            "item_Standard_Description": "Ultrasound - Kidney Urine Bladder",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "76770",
            "item_Description_of_Code": "Ultrasound, retroperitoneal (eg, renal, aorta, nodes), real time with image documentation",
            "item_Correct_Nomenclature": "Ultrasound - Kidney Urine Bladder/ USG KUB",
        },
        {
            "item_Standard_Code": 100192,
            "item_Standard_Description": "Ultrasound - Neck",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "24842-7",
            "item_Description_of_Code": "US Neck",
            "item_Correct_Nomenclature": "nan",
        },
        {
            "item_Standard_Code": 100193,
            "item_Standard_Description": "Ultrasound - Pelvis",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "76856",
            "item_Description_of_Code": "Under Diagnostic Ultrasound Procedures of the Pelvis Non-Obstetrical",
            "item_Correct_Nomenclature": "Ultrasound - Pelvis",
        },
        {
            "item_Standard_Code": 100194,
            "item_Standard_Description": "Ultrasound - Prostrate",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "76872",
            "item_Description_of_Code": "Ultrasound Transrectal (of Prostate)",
            "item_Correct_Nomenclature": "Ultrasound Transrectal Prostate/USG Prostrate",
        },
        {
            "item_Standard_Code": 100196,
            "item_Standard_Description": "Ultrasound - Scrotum",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "76870",
            "item_Description_of_Code": "Ultrasound, scrotum and contents",
            "item_Correct_Nomenclature": "USG - Scrotum",
        },
        {
            "item_Standard_Code": 100023,
            "item_Standard_Description": "Ultrasound - Thyroid",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "25010-0",
            "item_Description_of_Code": "US Thyroid gland",
            "item_Correct_Nomenclature": "USG - Thyroid gland",
        },
        {
            "item_Standard_Code": 100197,
            "item_Standard_Description": "Urine Albumin/Creatinine Ratio",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "32294-1",
            "item_Description_of_Code": "Albumin/Creatinine [Ratio] in Urine",
            "item_Correct_Nomenclature": "Urine-Albumin/Creatinine Ratio(UACR)",
        },
        {
            "item_Standard_Code": 100199,
            "item_Standard_Description": "Urine Creatinine",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "35674-1",
            "item_Description_of_Code": "Creatinine [Mass/volume] in Urine collected for unspecified duration",
            "item_Correct_Nomenclature": "Urine Creatinine",
        },
        {
            "item_Standard_Code": 100036,
            "item_Standard_Description": "Urine Nicotine",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "12293-7",
            "item_Description_of_Code": "Cotinine [Presence] in Urine",
            "item_Correct_Nomenclature": "Urine Cotinine Test (Qualitative)",
        },
        {
            "item_Standard_Code": 100200,
            "item_Standard_Description": "Urine-Protein/Creatinine Ratio",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "34366-5",
            "item_Description_of_Code": "Protein/Creatinine [Ratio] in Urine",
            "item_Correct_Nomenclature": "Urine-Protein/Creatinine Ratio(UPCR)",
        },
        {
            "item_Standard_Code": 100201,
            "item_Standard_Description": "VDRL",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "5292-8",
            "item_Description_of_Code": "Reagin Ab [Presence] in Serum by VDRL",
            "item_Correct_Nomenclature": "Venereal Disease Research Laboratory test-VDRL",
        },
        {
            "item_Standard_Code": 100202,
            "item_Standard_Description": "Very Low Density Lipids (VLDL)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "13458-5",
            "item_Description_of_Code": "Cholesterol in VLDL [Mass/volume] in Serum or Plasma by calculation",
            "item_Correct_Nomenclature": "Very Low Density Lipids (VLDL)",
        },
        {
            "item_Standard_Code": 100276,
            "item_Standard_Description": "Video MER",
            "item_Alias": false,
            "item_Type_of_Code": "Alinea Code",
            "item_Final_Code": "VMER-001",
            "item_Description_of_Code": "Video-Medical Examination Report",
            "item_Correct_Nomenclature": "Video-Medical Examination Report",
        },
        {
            "item_Standard_Code": 100162,
            "item_Standard_Description": "Vitamin B12",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "2132-9",
            "item_Description_of_Code": "Cobalamin (Vitamin B12) [Mass/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Vitamin B12 (Cobalamin/Serum B12)",
        },
        {
            "item_Standard_Code": 100203,
            "item_Standard_Description": "Vitamin D",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "14635-7",
            "item_Description_of_Code": "25-hydroxyvitamin D3 [Moles/volume] in Serum or Plasma",
            "item_Correct_Nomenclature": "Vitamin D 3 or Vitamin25 OH (hydroxy)",
        },
        {
            "item_Standard_Code": 100025,
            "item_Standard_Description": "WBC",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "6690-2",
            "item_Description_of_Code": "Leukocytes [#/volume] in Blood by Automated count",
            "item_Correct_Nomenclature": "White Blood Cells - WBC",
        },
        {
            "item_Standard_Code": 100237,
            "item_Standard_Description": "Widal(Tube Method)",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "13284-5",
            "item_Description_of_Code": "Salmonella typhi H D Ab [Presence] in Serum",
            "item_Correct_Nomenclature": "Widal test (Tube Method) for Typhoid",
        },
        {
            "item_Standard_Code": 100212,
            "item_Standard_Description": "X ray - Thoracolumbar lateral",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "72080",
            "item_Description_of_Code": "Radiologic examination, Spine; Thoracolumbar- AP and Lateral",
            "item_Correct_Nomenclature": "X ray - Thoracolumbar Spine- AP and Lateral",
        },
        {
            "item_Standard_Code": 100213,
            "item_Standard_Description": "X-Ray (IVP - Intravenous Pyleography)",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "74400",
            "item_Description_of_Code": "Urography (pyelography), intravenous, with or without KUB, with or without tomography",
            "item_Correct_Nomenclature": "X-Ray IVP - Intravenous Pyleography",
        },
        {
            "item_Standard_Code": 100214,
            "item_Standard_Description": "X-ray (Lumbo-Sacral)",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "72100",
            "item_Description_of_Code": "Radiologic examination, Spine; Lumbo-Sacral , AP and Lateral",
            "item_Correct_Nomenclature": "X ray - Lumbo-Sacral Spine - AP and Lateral/ X Ray LS Spine",
        },
        {
            "item_Standard_Code": 100205,
            "item_Standard_Description": "X-Ray - Abdomen GUT(2 Plates) - XRB",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "74019",
            "item_Description_of_Code": "Radiologic examination, Abdomen; 2 views",
            "item_Correct_Nomenclature": "X-Ray - Abdomen GUT (2 plates/2 views)",
        },
        {
            "item_Standard_Code": 100206,
            "item_Standard_Description": "X-Ray - Abdomen GUT(Plate 1) - XRA",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "74018",
            "item_Description_of_Code": "Radiologic examination, Abdomen; 1 view",
            "item_Correct_Nomenclature": "X-Ray - Abdomen GUT(1 plate/1 view)",
        },
        {
            "item_Standard_Code": 100207,
            "item_Standard_Description": "X-Ray - Barium Enema",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "74270",
            "item_Description_of_Code": "Radiologic examination, colon; contrast (eg, barium) enema, with or without KUB",
            "item_Correct_Nomenclature": "X-Ray - Barium Enema)",
        },
        {
            "item_Standard_Code": 100208,
            "item_Standard_Description": "X-Ray - Cholecystography",
            "item_Alias": false,
            "item_Type_of_Code": "Loinc Code",
            "item_Final_Code": "36001-6",
            "item_Description_of_Code": "XR tomography Gallbladder",
            "item_Correct_Nomenclature": "X-Ray Gall Bladder/ X Ray Cholecystography",
        },
        {
            "item_Standard_Code": 100209,
            "item_Standard_Description": "X-Ray - Dorsal Spine",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "72070",
            "item_Description_of_Code": "Radiologic examination, Spine; Thoracic/Dorsal , AP and Lateral",
            "item_Correct_Nomenclature": "X ray - Thoracic/Dorsal Spine- AP and Lateral",
        },
        {
            "item_Standard_Code": 100210,
            "item_Standard_Description": "X-Ray - KUB",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "74018",
            "item_Description_of_Code": "X-Ray Abdomen KUB 1 view",
            "item_Correct_Nomenclature": "X-Ray KUB",
        },
        {
            "item_Standard_Code": 100211,
            "item_Standard_Description": "X-Ray - Right Hand",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "73120",
            "item_Description_of_Code": "Radiologic examination of the hand, minimum of two views.",
            "item_Correct_Nomenclature": "X ray - Right Hand",
        },
        {
            "item_Standard_Code": 100212,
            "item_Standard_Description": "X-Ray - Thoracolumbar lateral",
            "item_Alias": false,
            "item_Type_of_Code": "CPT Code",
            "item_Final_Code": "72080",
            "item_Description_of_Code": "X Ray Thoraco-Lumbar",
            "item_Correct_Nomenclature": "X Ray Thoraco-Lumbar",
        }
]